# Generated by Django 5.0.7 on 2024-07-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Kickstart your Next.JS 14 website in minutes', max_length=255, verbose_name='Título')),
            ],
            options={
                'verbose_name': 'Sessão Hero',
                'verbose_name_plural': 'Sessões Hero',
            },
        ),
    ]
