# Generated by Django 5.0.7 on 2024-07-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='highlight_term',
            field=models.CharField(default='', max_length=100, verbose_name='Termo destacado to título'),
            preserve_default=False,
        ),
    ]
