# Generated by Django 5.0.7 on 2024-07-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heros', '0002_hero_highlight_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='img',
            field=models.ImageField(default='hero_img.jpg', upload_to=''),
        ),
    ]
