# Generated by Django 5.0.7 on 2024-07-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heros', '0003_hero_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='text',
            field=models.TextField(default='Inators UI is a collection of UI components and templates based on Tailwind and Shadcn/ui, just copy and use', verbose_name='text'),
        ),
    ]
