# Generated by Django 5.0.7 on 2024-08-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Título')),
                ('subtitle', models.CharField(default='', max_length=255, verbose_name='Subtítulo')),
                ('cta_text', models.CharField(default='', max_length=100, verbose_name='Texto do botão')),
                ('cta_link', models.CharField(default='', max_length=100, verbose_name='Link do botão')),
            ],
            options={
                'verbose_name': 'Banner',
            },
        ),
    ]
