# Generated by Django 5.0.7 on 2024-07-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Nome')),
                ('code', models.TextField(verbose_name='Código SVG')),
            ],
            options={
                'verbose_name': 'Ícone',
            },
        ),
    ]
