# Generated by Django 5.0.7 on 2024-07-19 21:31

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_versions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteversion',
            options={'verbose_name': 'Versão do site', 'verbose_name_plural': 'Versões do site'},
        ),
        migrations.AddField(
            model_name='siteversion',
            name='main_color',
            field=colorfield.fields.ColorField(default='#e11d48', image_field=None, max_length=25, samples=None),
        ),
    ]
