# Generated by Django 5.0.7 on 2024-07-20 13:38

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_versions', '0002_alter_siteversion_options_siteversion_main_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteversion',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Versão principal?'),
        ),
        migrations.AlterField(
            model_name='siteversion',
            name='main_color',
            field=colorfield.fields.ColorField(default='#e11d48', image_field=None, max_length=25, samples=None, verbose_name='Cor principal'),
        ),
        migrations.AlterField(
            model_name='siteversion',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
    ]
