# Generated by Django 5.0.7 on 2024-07-20 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heros', '0001_initial'),
        ('site_versions', '0003_siteversion_active_alter_siteversion_main_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteversion',
            name='hero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='heros.hero', verbose_name='Sessão Hero'),
        ),
    ]
