# Generated by Django 5.0.7 on 2024-07-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
        ('site_versions', '0005_siteversion_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteversion',
            name='features',
            field=models.ManyToManyField(to='features.feature', verbose_name='Funcionalidades'),
        ),
    ]
