# Generated by Django 5.0.7 on 2024-08-02 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
        ('site_versions', '0006_siteversion_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteversion',
            name='banner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banners.banner', verbose_name='Banner'),
        ),
    ]
