# Generated by Django 5.0.7 on 2024-08-02 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
        ('site_versions', '0007_siteversion_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteversion',
            name='faq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='faqs.faq', verbose_name='Sessão de perguntas e respostas'),
        ),
    ]
