# Generated by Django 5.0.7 on 2024-07-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='\nMake Next.js 14 your new playground', max_length=255, verbose_name='Título')),
                ('subtitle', models.CharField(default='\nEasy to use UI elements based on Tailwind CSS and Shadcn/ui', max_length=255, verbose_name='Subtítulo')),
                ('text', models.TextField(default='Inators UI is a toolkit for developers and designers to make creating nextjs client side as well as server side interfaces easier. Using Shadcn-ui components as base and added missing necessary components, Inators UI have multiple components to help you get started. Everything is modular and customizable to fit your project. From cards to buttons to blogs, you can quickly create a variety of layouts that is responsible for next.js 14 and look great on any screen.', verbose_name='Texto')),
                ('img', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Funcionalidade',
            },
        ),
    ]
