# Generated by Django 5.0.7 on 2024-08-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Pergunta')),
                ('answer', models.CharField(max_length=255, verbose_name='Resposta')),
            ],
            options={
                'verbose_name': 'Pergunta',
            },
        ),
    ]
