# Generated by Django 5.0.7 on 2024-08-02 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0002_faqitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqitem',
            name='faq_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='faqs.faq'),
        ),
    ]
