# Generated by Django 5.0.7 on 2024-08-02 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0003_faqitem_faq_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='subtitle',
            field=models.CharField(default='', max_length=255, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='faq_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_items', to='faqs.faq'),
        ),
    ]
