# Generated by Django 5.0.7 on 2024-07-30 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0001_initial'),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='icons.icon', verbose_name='Ícone'),
        ),
    ]
